Vagrant.configure(2) do |config|
    config.vagrant.plugins = ["vagrant-reload"]

    config.vm.network "private_network", bridge: "Default Switch"
    config.vm.synced_folder ".", "/vagrant", :disabled => true

    config.vm.define :etcd do |etcd|
      etcd.vm.host_name = "etcd"
      etcd.vm.box = "hashicorp/bionic64"

      etcd.vm.provider :hyperv do |hv|
        hv.memory = 4096
        hv.cpus = 2
        hv.linked_clone = true
        hv.maxmemory = 4096
      end
    end

    config.vm.define :controlplane do |controlplane|
      controlplane.vm.host_name = "controlplane"
      controlplane.vm.box = "hashicorp/bionic64"

      controlplane.vm.provider :hyperv do |hv|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        hv.maxmemory = 4096
      end
    end

    config.vm.define :worker do |worker|
      worker.vm.host_name = "worker"
      worker.vm.box = "hashicorp/bionic64"

      worker.vm.provider :hyperv do |hv|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        hv.maxmemory = 4096
      end
    end

    config.vm.define :winworker do |winworker|
      winworker.vm.host_name = "winworker"
      winworker.vm.box = "jborean93/WindowsServer2019"

      winworker.vm.provider :hyperv do |hv, override|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        override.vm.boot_timeout = 600
      end

      winworker.vm.provision :shell, privileged: true, inline: "Install-WindowsFeature -Name Containers"
      winworker.vm.provision :reload
    end

    config.vm.define :winworker22 do |winworker22|
      winworker22.vm.host_name = "winworker22"
      winworker22.vm.box = "jborean93/WindowsServer2022"

      winworker22.vm.provider :hyperv do |hv, override|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        override.vm.boot_timeout = 600
      end

      winworker22.vm.provision :shell, privileged: true, inline: "Install-WindowsFeature -Name Containers"
      winworker22.vm.provision :reload
    end

    config.vm.define :rkewin do |rkewin|
      rkewin.vm.host_name = "rkewin"
      rkewin.vm.box = "StefanScherer/windows_2019_docker"

      rkewin.vm.provider :hyperv do |hv, override|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        override.vm.boot_timeout = 600
      end
    end

    config.vm.define :rancher do |rancher|
      rancher.vm.host_name = "rancher"
      rancher.vm.box = "hashicorp/bionic64"

      rancher.vm.provider :hyperv do |hv|
        hv.memory = 8192
        hv.cpus = 2
        hv.linked_clone = true
      end

      rancher.vm.provision :shell, privileged: true, inline: "snap install docker"
      rancher.vm.provision :shell, privileged: true, inline: "snap install kubectl --classic"
      rancher.vm.provision :shell, privileged: true, inline: "docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.6.3"

    end

  end
