Vagrant.configure(2) do |config|
    config.vagrant.plugins = ["vagrant-libvirt", "vagrant-reload"]

    config.vm.provider :hyperv do |config|
        config.vm.network "private_network", bridge: "Default Switch"
    end


    config.vm.synced_folder ".", "/vagrant", :disabled => true

    config.vm.define :etcd do |etcd|
      etcd.vm.host_name = "etcd"
      etcd.vm.box = "generic/ubuntu1804"

      etcd.vm.provider :libvirt do |libvirt|
        libvirt.memory = 4096
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      etcd.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end

      etcd.vm.provider :hyperv do |hv|
        hv.memory = 4096
        hv.cpus = 2
        hv.linked_clone = true
      end
    end

    config.vm.define :controlplane do |controlplane|
      controlplane.vm.host_name = "controlplane"
      controlplane.vm.box = "generic/ubuntu1804"

      controlplane.vm.provider :libvirt do |libvirt|
        libvirt.memory = 4096
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      controlplane.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end

      controlplane.vm.provider :hyperv do |hv|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
      end
    end

    config.vm.define :worker do |worker|
      worker.vm.host_name = "worker"
      worker.vm.box = "generic/ubuntu1804"

      worker.vm.provider :libvirt do |libvirt|
        libvirt.memory = 4096
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      worker.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end

      worker.vm.provider :hyperv do |hv|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
      end
    end

    config.vm.define :winworker do |winworker|
      winworker.vm.host_name = "winworker"
      winworker.vm.box = "jborean93/WindowsServer2019"

       winworker.vm.provider :libvirt do |libvirt|
        libvirt.memory = 8192
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      winworker.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
        vb.gui = true
      end

      winworker.vm.provider :hyperv do |hv, override|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        override.vm.boot_timeout = 600
      end

      winworker.vm.provision :shell, privileged: true, inline: "Write-Host 'Installing Containers Feature...'"
      winworker.vm.provision :shell, privileged: true, inline: "Install-WindowsFeature -Name Containers"
      winworker.vm.provision :reload
      winworker.vm.provision :shell, privileged: true, inline: "Set-NetFirewallProfile -Profile Domain, Public, Private -Enabled False"
    end

    config.vm.define :winworker22 do |winworker22|
      winworker22.vm.host_name = "winworker22"
      winworker22.vm.box = "jborean93/WindowsServer2022"

      winworker22.vm.provider :libvirt do |libvirt|
        libvirt.memory = 8192
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      winworker22.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
        vb.gui = true
      end

      winworker22.vm.provider :hyperv do |hv, override|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        override.vm.boot_timeout = 600
      end
    end

    config.vm.define :rancher do |rancher|
      rancher.vm.host_name = "rancher"
      rancher.vm.box = "generic/ubuntu1804"

      rancher.vm.provider :libvirt do |libvirt|
        libvirt.memory = 4096
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      rancher.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end

      rancher.vm.provider :hyperv do |hv|
        hv.memory = 4096
        hv.cpus = 2
        hv.linked_clone = true
      end

      rancher.vm.provision :shell, privileged: true, inline: "apt-get update && apt-get install build-essential -y"
      rancher.vm.provision :shell, privileged: true, inline: "snap install docker"
      rancher.vm.provision :shell, privileged: true, inline: "snap install kubectl --classic"
      rancher.vm.provision :shell, privileged: true, inline: "docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.6-head"

    end

    config.vm.define :ad do |ad|
      ad.vm.host_name = "ad"
      ad.vm.box = "jborean93/WindowsServer2019"

       ad.vm.provider :libvirt do |libvirt|
        libvirt.memory = 8192
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      ad.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
        vb.gui = true
      end

      ad.vm.provider :hyperv do |hv, override|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        override.vm.boot_timeout = 600
      end

      ad.vm.provision :shell, privileged: true, inline: "Set-NetFirewallProfile -Profile Domain, Public, Private -Enabled False"
    end

  config.vm.define :control, primary: true do |control|
    control.vm.host_name = "rke2control"
    control.vm.box = "opensuse/Leap-15.3.x86_64"
    control.vm.provider :libvirt do |libvirt|
      libvirt.memory = 8192
      libvirt.cpus = 2
      libvirt.disk_driver :cache => 'none'
    end

    control.vm.provision :shell, privileged: true, inline: "zypper --non-interactive install hostname"
  end
  end
