Vagrant.configure(2) do |config|
    config.vagrant.plugins = ["vagrant-libvirt", "vagrant-reload"]

    config.vm.provider :hyperv do |config|
        config.vm.network "private_network", bridge: "Default Switch"
    end
    config.vm.synced_folder ".", "/vagrant", :disabled => true

    config.vm.define :main do |main|
      main.vm.host_name = "main"
      main.vm.box = "generic/ubuntu1804"

      main.vm.provider :libvirt do |libvirt|
        libvirt.memory = 4096
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      main.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end
      main.vm.provider :hyperv do |hv|
        hv.memory = 4096
        hv.cpus = 2
      end

      #main.vm.synced_folder "./sync", "/var/sync"
     
      #main.vm.provision :shell, privileged: true, path: "main.sh"
    end
  
    config.vm.define :linuxworker do |linuxworker|
      linuxworker.vm.host_name = "linuxworker"
      linuxworker.vm.box = "generic/ubuntu1804"

      linuxworker.vm.provider :libvirt do |libvirt|
        libvirt.memory = 4096
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      linuxworker.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end
      linuxworker.vm.provider :hyperv do |hv|
        hv.linked_clone = true
        hv.memory = 4096        
        hv.cpus = 2
      end

      #linuxworker.vm.synced_folder "./sync", "/var/sync", smb_username: ENV['SMB_USERNAME'], smb_password: ENV['SMB_PASSWORD']
      #linuxworker.vm.provision :shell, privileged: true, path: "linuxworker.sh"
    end

    config.vm.define :winworker do |winworker|
      winworker.vm.host_name = "winworker"
      winworker.vm.box = "jborean93/WindowsServer2019"

      winworker.vm.provider :libvirt do |libvirt|
        libvirt.memory = 8192
        libvirt.cpus = 2
        libvirt.disk_driver :cache => 'none'
      end

      winworker.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
        vb.gui = true
      end 
      winworker.vm.provider :hyperv do |hv, override|  
        hv.linked_clone = true  
        hv.memory = 4096
        hv.cpus = 2
        override.vm.boot_timeout = 600
      end

      winworker.vm.provision :shell, privileged: true, inline: "Write-Host 'Installing Containers Feature...'"
      winworker.vm.provision :shell, privileged: true, inline: "Install-WindowsFeature -Name Containers"
      winworker.vm.provision :reload
      #winworker.vm.synced_folder "./sync", "C:/sync"
      #winworker.vm.provision :shell, privileged: true, path: "winworker.ps1"
    end
    
  end
