Vagrant.require_version ">= 2.2.17"
Vagrant.configure(2) do |config|
    # Need this to reboot Windows after enabling Containers feature.
    config.vagrant.plugins = ["vagrant-reload", "vagrant-rke2"]

    config.vm.network "private_network", bridge: "Default Switch"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    rke2_version = "v1.22.6+rke2r1"

    config.vm.define :server do |server|
      server.vm.host_name = "server"
      server.vm.box = 'bento/ubuntu-20.04'
      server.vm.provider :hyperv do |hv|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        hv.maxmemory = 4096
      end

      server.vm.provision :rke2, run: "once" do |rke2|
        rke2.env = <<~ENV
        INSTALL_RKE2_VERSION=#{rke2_version}
        INSTALL_RKE2_TYPE=server
        ENV

        rke2.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
        rke2.config = <<~YAML
          write-kubeconfig-mode: 0644
          token: vagrant-rke2
          cni: calico
        YAML
      end
    end

    config.vm.define :linuxagent do |linuxagent|
      linuxagent.vm.host_name = "linuxagent"
      linuxagent.vm.box = "bento/ubuntu-20.04"
      linuxagent.vm.provider :hyperv do |hv|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        hv.maxmemory = 4096
      end

      linuxagent.vm.provision :rke2, run: "once" do |rke2|
        rke2.env = <<~ENV
        INSTALL_RKE2_VERSION=#{rke2_version}
        INSTALL_RKE2_TYPE=agent
        ENV

        rke2.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
        rke2.config = <<~YAML
          write-kubeconfig-mode: 0644
          server: https://server:9345
          token: vagrant-rke2
        YAML
      end
    end

    config.vm.define :winagent do |winagent|
      winagent.vm.host_name = "winagent"
      winagent.vm.box = "jborean93/WindowsServer2019"
      winagent.vm.provider :hyperv do |hv, override|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        override.vm.boot_timeout = 600
      end

      winagent.vm.provision :rke2, run: "once" do |rke2|
        rke2.env = "-Version #{rke2_version}"
        rke2.config = <<~YAML
          kube-proxy-arg: "feature-gates=IPv6DualStack=false"
          server: https://server:9345
          token: vagrant-rke2
        YAML
      end
    end

    config.vm.define :winagent22 do |winagent22|
      winagent22.vm.host_name = "winagent22"
      winagent22.vm.box = "jborean93/WindowsServer2022 "
      winagent22.vm.provider :hyperv do |hv, override|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        override.vm.boot_timeout = 600
      end

      winagent22.vm.provision :rke2, run: "once" do |rke2|
        rke2.env = "-Version #{rke2_version}"

        rke2.config = <<~YAML
          kube-proxy-arg: "feature-gates=IPv6DualStack=false"
          server: https://server:9345
          token: vagrant-rke2
        YAML
      end
    end
end
