
Vagrant.configure(2) do |config|
    config.vagrant.plugins = ["vagrant-reload"]

    config.vm.network "private_network", bridge: "External"
    config.vm.synced_folder ".", "/vagrant", :disabled => true

    config.vm.define :squid do |squid|
      squid.vm.host_name = "squid"
      squid.vm.box = "hashicorp/bionic64"

      squid.vm.provider :hyperv do |hv|
        hv.linked_clone = true
        hv.memory = 4096
        hv.cpus = 2
        hv.maxmemory = 4096
      end

      squid.vm.provision :shell, privileged: true, inline: "snap install docker"
      squid.vm.provision :file, source: "squid.conf", destination: "/home/vagrant/squid/squid.conf"
      squid.vm.provision :shell, privileged: true, inline: "docker run -d -v /home/vagrant/squid/squid.conf:/etc/squid/squid.conf -p 3128:3128 wernight/squid"
    end

    config.vm.define :registry do |registry|
      registry.vm.host_name = "registry"
      registry.vm.box = "hashicorp/bionic64"
      registry.vm.disk :disk, size: "100GB"
      registry.vm.provider :hyperv do |hv|
        hv.linked_clone = true
        hv.memory = 8192
        hv.cpus = 4
        hv.maxmemory = 8192
      end

      registry.vm.provision :shell, privileged: true, inline: "apt-get update"
      registry.vm.provision :shell, privileged: true, inline: "apt-get install -y \
        ca-certificates \
        curl \
        gnupg \
        lsb-release"

      registry.vm.provision :shell, privileged: true, inline: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

      registry.vm.provision :shell, privileged: true, inline: "echo \
        \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable\" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"
      registry.vm.provision :shell, privileged: true, inline: "apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin"

      registry.vm.provision :shell, privileged: true, inline: "docker run -d -p 5000:5000 --restart=always --name registry registry:2"

      registry.vm.provision :shell, privileged: true, inline: "wget https://github.com/rancher/rancher/releases/download/v2.6.5-rc5/rancher-images.txt && \
        wget https://github.com/rancher/rancher/releases/download/v2.6.5-rc5/rancher-save-images.sh && \
        wget https://github.com/rancher/rancher/releases/download/v2.6.5-rc5/rancher-load-images.sh"

      registry.vm.provision :shell, privileged: true, inline: "sudo sed -i '58d' rancher-save-images.sh && \
        sudo sed -i '76d' rancher-load-images.sh && \
        chmod +x rancher-save-images.sh && chmod +x rancher-load-images.sh"
       
      registry.vm.provision :shell, privileged: true, inline: "./rancher-save-images.sh --image-list ./rancher-images.txt"
      registry.vm.provision :shell, privileged: true, inline: "./rancher-load-images.sh --image-list ./rancher-images.txt --registry localhost:5000"
 

    end

  end
